name: Lambda Deploy via S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      FUNCTION_NAME: SeedToScoreFunction
      S3_BUCKET: seed-to-score-lambda-code
      S3_KEY: lambda/function.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Zip Lambda function
        run: |
          cd lambda_build/output
          zip -r function.zip .

      - name: Upload ZIP to S3
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          args: s3 cp lambda_build/output/function.zip s3://${{ env.S3_BUCKET }}/${{ env.S3_KEY }}

      - name: Deploy Lambda from S3
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          args: lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --s3-bucket ${{ env.S3_BUCKET }} --s3-key ${{ env.S3_KEY }}
